### ISSUE TITLE
$HOME symlinked to /storage/sdcard1/droidvim/home ?

### ISSUE THREAD

**Issue by philiprhoades** [shiftrot/droidvim#14]
People,

I want to so the above but I get errors on editing .vimrc and other files - I presume because of ownership permissions. However chowning and chmoding doesn't work . . 

Is there a solution?

Thanks,
Phil.

**Comment by shiftrot** [comment]
1. Normal SD cards are not formatted for Linux. Therefore chmod does not work.
2. For security reasons, access to files on the SD card is only allowed via "Storage" button (Android API).

On some devices, you can access files on the SD card directly from DroidVim. But that is exceptional behavior.

**Comment by shiftrot** [comment]
> Ah yes . . I see - is it possible to format the SD partition as ext4?

Android does not support ext4 formatted SD card.

> The Storage Button idea is a bit of a pain though - I want to edit any text file I want on any partitions - directly . . like I can with the editor in the X-Plore File Manager and other FMs.

If you want a filer like X-Plore FM, please use DroidVim via X-Plore FM.
Incidentally, X-Plore File Manager (and many FMs) can not access SD card on Android 8.x.
However, because the "storage" button uses the Android standard framework, it works with all versions of Android.

> What do you mean "security reasons"?

Ask Google. 

> how can I enable this "exceptional behaviour".

Root Android or get an Android device that supports Adoptable storage. However, I do not guarantee that it will work.
It would be better to get an Android device with large internal storage.

**Comment by philiprhoades** [comment]
@shiftrot ,

Things developed a little from you last post!:

1. I took your advice and stopped using link2SD and reformatted the SD card as Adoptable storage - this substantially solved my problems
2. Then the phone itself started playing up - I am pretty convinced it is the USB connector for charging again - I had to replace that little board a few years ago . .
3. Because of #2 I had to get another phone (Google Pixel 2XL) - it was the biggest I could get with Google (because of its more sympathetic position to rooting etc)
4. Now I have a different problem with DroidVim but I will start another issue for that . .

Thanks!
Phil.
