### ISSUE TITLE
Open 2 Dropbox files simultaneously

### ISSUE THREAD

**Issue by igavronski** [shiftrot/droidvim#2]
Hi,

I could not figure out how to open two files residing in Dropbox at the same time.

:e ?

Regards,

Iuri.

**Comment by shiftrot** [comment]
Because DroidVim opens a file using the Dropbox application function, it can not select and open multiple files.
But once opened files do not need to be opened via the file picker. So once you open the file, it is a good idea to select multiple files using Vim's MRU plugin with multiple selection function.
Personally, I use Dropsync to make copies of frequently used directories and sync, and I use DroidVim's "Dropbox" menu only for other files.
