### ISSUE TITLE
Bugs with hebrew typing

### ISSUE THREAD

**Issue by elig0n** [shiftrot/droidvim#24]
### Background
Experienced on DroidVim 1.3
Tested with fonts: System font, "Miriam Fixed" and "Elronet Monospace".
Default configuration.
AOSP keyboard with Hebrew layout.

### The problem
Characters inserted in hebrew layout show up with the last letter of each word get carried along with a "space" to the beginning of the next word. 

Example (in english):

    Thi sI sTh eProble m

The last letter is also "carried" when several spaces are appended after a word.

With `:set rightleft` another symptom show up which involves the last character of a line ends up on the other edge of the screen. Example:

    Anothe rSympto                                                                      m
    An dAnothe rLin                                                                     e

(of course the text is in hebrew and the direction of the text is RTL)

**Comment by shiftrot** [comment]
It is a problem that occurs because not using monospaced fonts.
I recommend using a font that displays Hebrew properly even with GVim.

Although it is possible to display even if it is not a monospaced font, there is a problem in drawing speed.
There are no serious functional issues other than drawing speed, so I added an option to the "Fonts" section of the beta (just scroll down the Play Store page). Try it if you're interested or wait for the next update.

**Comment by elig0n** [comment]
Like I said, I tried different fonts and the problem persists.

**Comment by shiftrot** [comment]
You can NOT use proportional fonts with Vim.
Make sure that the font you are using is a monospaced font.
If you want to use proportional fonts, use the beta and enable the "proportional font" option.
