### ISSUE TITLE
Terminal emulator background is not always black

### ISSUE THREAD

**Issue by eevan78** [shiftrot/droidvim#28]
I'm not sure if this is related to the DroidVim, but I have to ask.
I run it on LineageOS 16 (Android 9) on Galaxy S7 Edge.
I wanted to set the pure black terminal background, but I have noticed that the terminal window background color changes depending on the location of the cursor focus.

Related settings:

- Terminal: screen-256color
- Text color setting: Linux console (I have tried with other choices, the behaviour is same)
- Customized Vim colorscheme

So, this is the screenshot when the cursor is located in one-line textbox (background is true black):
![Screenshot_20191211-105933_DroidVim1](https://user-images.githubusercontent.com/27575106/70606157-5e49b080-1c15-11ea-8bca-7a0894a73037.png)

And this is the screenshot when the focus is in the terminal window, in the text (not pure black):
![Screenshot_20191211-105946_DroidVim1](https://user-images.githubusercontent.com/27575106/70606301-97822080-1c15-11ea-90cf-1814a6e70cc1.png)

Other that this, I haven't encountered any problems.

**Comment by shiftrot** [comment]
The simplest solution is to set the theme to "Light theme".

This problem is due to side effects of processing that Android OS performs to improve visibility, and the behavior varies depending on the OS version. (This is because Android does not assume an application like a terminal emulator.)
I guess there might be a technical workaround by creating a custom theme, but this is not clear at this time. 

I added it to the To Do list for the time being, so I would like to fix it when I have time.
Thanks.

**Comment by shiftrot** [comment]
Please try Beta (scroll down the Play Store page) or wait for the next update.

**Comment by eevan78** [comment]
I have tried the beta, and dark theme (API26) works perfectly!
Thanks for fixing the issue!

уто, 17. дец 2019. 17:31 shiftrot <notifications@github.com> је написао/ла:
