### ISSUE TITLE
su command returns "connection reset by peer"

### ISSUE THREAD

**Issue by crash5** [shiftrot/droidvim#36]
Phone: Xiaomi MI9
ROM: MIUI 12 (xiaomi.eu 20.8.20)
Rooted, Magisk v24.4, Magisk Manager v7.5.1

My goal is to edit system files with droidvim like wpa_supplicant etc.

I tried these steps from the F.A.Q in `:shell` but always get the result as in the screenshot.
```
busybox-setup sysbin
---
busybox-setup sysbin su
---
busybox-setup clean
busybox-setup 
```

![Screenshot_2020-08-29-10-55-07-996_com droidvim](https://user-images.githubusercontent.com/10976627/91633270-34286080-e9e7-11ea-89bf-d3d3c23ac8fc.png)

**Comment by shiftrot** [comment]
I'm not sure why the error happened, because I don't have rooted device now.
Please change [Settings] -> [Shell] -> [Initial Command] as follows, then restart DroidVim.
```
#bash
#-vim.app
unset LD_LIBRARY_PATH
```
With this setting, it will start up as a simple terminal emulator.
Please let me know the result of executing "su".

**Comment by crash5** [comment]
Results in the same error message as in the first post.

**Comment by shiftrot** [comment]
Could you try setting [Initial Commands] as follows to see if it works?
```
cd %STARTUP_DIR%
#bash
#-vim.app
unset LD_LIBRARY_PATH
rm -rf $APPFILES/usr/bin
su
```

After trying it, set [Initial Commands] as follows and "Menu Extras (Drawer Menu)">"System Recovery", DroidVim will work.
```
cd %STARTUP_DIR%
bash
-vim.app
```

If this doesn't work, it's probably due to Proot (Required to bypass Android 10+ issue).
Perhaps it's not difficult to fix to make su work, but I think you'll need to switch between DroidVim's "Normal mode" and "su mode" and restart DroidVim App.
It may not be convenient, so it may be better to use another terminal emulator.
I'll implement it anyway. But I don't have a rooted Android 10+ device.
Could you test it?

**Comment by crash5** [comment]
Same error message. How can I switch to "su mode"?
Most of the time I open files with android "open with/share to droidvim" functionality which is not supported in terminal emulators.

![com droidvim](https://user-images.githubusercontent.com/10976627/91747286-2f69d500-ebbe-11ea-805e-ecaaeb924b06.png)

**Comment by shiftrot** [comment]
Please update to the beta version (scroll down the Play Store page).
Once Vim is up, do the following.
1. :TerminalMode
2. Restart DroidVim
3. su

The execution result can also be copied by "Long press menu"> "Screen"> "Copy screen buffer".

If it does not work, try following.
1. :TerminalMode sh
2. Restart DroidVim
3. su

If either goes well, you may be able to use Vim with root privileges by running `suvim` instead of `su`.
To start Vim from shell under root environment, you need to use a shell script like `$APPFILES/bin/vim.sh`.

Thanks.

**Comment by crash5** [comment]
After :TerminalMode and restart su works and I can start vim as root. But the next run vim starts up and su/suvim broken again in :shell. (I tried to use suvim in initial command setting instead of vim but results in the same error message as the beginning)

**Comment by shiftrot** [comment]
That's what I intended.
Use of su should be kept to a minimum, so closing DroidVim will switch to general user mode.

**Comment by crash5** [comment]
Can you add a menu entry to the android "share/open with" menu to open with DroidEdit (root)? (Maybe an optional icon to the desktop/homescreen to start droidedit as root?)

**Comment by shiftrot** [comment]
Contact the DroidEdit developer.

**Comment by crash5** [comment]
Oh, sorry I meant DroidVim.

**Comment by shiftrot** [comment]
After this, I'm going to improve suvim a little, but I don't think I'll add a root shortcut. (Since I don't have a rooted device)
