### ISSUE TITLE
Can't totally trust dropbox syncing

### ISSUE THREAD

**Issue by m2habert** [shiftrot/droidvim#39]
It is a great feature, but: sometimes it is working great; 
and sometimes, out of the blue, dropbox refuses to acknowledge that there is file change. 

Thus, if one closes droidvim, all changes are lost.

My personal problem is that I use dVim sporadicallly, and many times I resort to it with that "trustworty memory" that "it was working great last time", which, obviously, whenever this bug happens, leads to a big frustration.

¿Anything I may be doing wrong? 

¿Any tips on creating some temp file safeguard just in case things go sour?

thanks!

**Comment by shiftrot** [comment]
I have confirmed and fixed this issue.
Updates will be available soon, so give it a try.
Thank you!

**Comment by m2habert** [comment]
Wow!

And here I the pessimist thinking it would be a hard-to-reproduce bug...  Thank you kindly, @shiftrot !

**Comment by shiftrot** [comment]
It wasn't difficult because it was a careless mistake😅
This was a very useful bug report.  Thanks again!

**Comment by m2habert** [comment]
I've just upgraded dVim and the sync is working great for online changes.

But: I tested a file change while offline (setting file to be available offline from the dropbox app + setting wifi off) and, upon reactivating wifi a half an hour afterwards, my changes were lost.

I remember that this used to work, no?

**Comment by shiftrot** [comment]
After updating an offline file in DroidVim, check if you see Dropbox notification.
If you see the notification, Dropbox app will handle everything after that.

As far as I know, Dropbox doesn't update or seems to be delayed unless you tap the Dropbox notification after you're online.

**Comment by m2habert** [comment]
You're right, I remember now that it used to happen that way.

And I've just tested, and no notification shows up, as you predicted.

**Comment by shiftrot** [comment]
I found a way to prevent Dropbox files from being updated in an external editor (not just DroidVim). The cause of this issue may be a bug in Dropbox's offline processing.

How to deal with this issue is currently undecided.

**Comment by shiftrot** [comment]
Probably the cause is an update that Dropbox made to support SAF (Android Storage Access Framework).
The beta version of DroidVim has reduced writes to the SAF. If you want to give it a try, please use the beta version (scroll down the Play Store page).
This is not a DroidVim specific issue and I don't think it will be resolved until Dropbox is updated.
I recommend not editing offline for now (even if you are using an editor other than DroidVim).

In my environment, using only an editor other than DroidVim had the same problem and I couldn't write without reinstalling Dropbox. FYI.

**Comment by m2habert** [comment]
¿Wouldn't be a nice touch for droidvim to save temp files somewhere the user could access in case of sync failure?

I know it may seem like too much user-moping, but it probably could be useful in other human errors... And, just like ALWAYS, this dropbox >< google guidelines issue points to future sync problems even when this one is solved...

**Comment by shiftrot** [comment]
> ¿Wouldn't be a nice touch for droidvim to save temp files somewhere the user could access in case of sync failure?

See `:help backup`.
I recommend using Google Drive or Dropsync or keep online.

> I know it may seem like too much user-moping, but it probably could be useful in other human errors... And, just like ALWAYS, this dropbox >< google guidelines issue points to future sync problems even when this one is solved...

What does "this dropbox >< google guidelines issue" mean?

The underlying problem is that Dropbox expects the device to stay online at all times. 
In fact, most users use their device online, so it doesn't matter. 
Prior to supporting ASF, Dropbox used files in the device's internal storage as cache files, so it didn't matter if the device was offline.

**Comment by shiftrot** [comment]
Please try using the beta version.
- Warning if offline write fails
- Made it harder for Dropbox to make conflicting copies

If you use the overwrite button when an offline write fails, you will not get a write error, but you will lose your edit state.
