### ISSUE TITLE
Publishing on F-droid

### ISSUE THREAD

**Issue by opk12** [shiftrot/droidvim#50]
F-droid has a [packaging request](https://gitlab.com/fdroid/rfp/-/issues/1443) for this app. Entering the repo is blocked for the reasons summarized in [this comment](https://gitlab.com/fdroid/rfp/-/issues/1443#note_856506979).
1. Could you publish the scripts to rebuild the precompiled binaries (the file list is [here](https://gitlab.com/fdroid/rfp/-/issues/1443#note_392926281))?
2. The 0-byte [`MODULE_LICENSE_APACHE2`](https://github.com/shiftrot/droidvim/blob/master/MODULE_LICENSE_APACHE2) is not sufficient, the complete license text needs to be added.

**Comment by shiftrot** [comment]
> Could you publish the scripts to rebuild the precompiled binaries (the file list is here)?

All binaries are simply a cross-compilation of the publicly available source using Ubuntu. (The sources are unmodified. Docker is not used).
Perhaps you need to rewrite the script for the virtual environment supported by F-droid.

Termux (published on F-droid) downloads and links pre-compiled binaries from Github.
Rather than using a script, it would be easier to create a DroidVim repository for F-droid and modify it to download binaries in the same way as Termux.
https://github.com/termux/termux-app/blob/master/app/build.gradle
(See downloadBootstrap())

I think the way Termux is built and the way DroidVim is built are essentially the same.
Since I am not familiar with F-droid, could you please tell me what logic F-droid uses to distinguish between the two and reject DroidVim?

> The 0-byte MODULE_LICENSE_APACHE2 is not sufficient, the complete license text needs to be added.

I'm planning to add it in the next update.

**Comment by opk12** [comment]
Thanks, I pointed the F-Droid people to your reply. [Here](https://gitlab.com/fdroid/fdroiddata/-/issues/2614) is the issue for Termux. Downloading a distro after installation is Termux's stated purpose and a security issue by itself, so working to postpone the download to the runtime might not be worth the effort.

**Comment by shiftrot** [comment]
I'm not talking about the distros that Termux users download.

The Termux apk distributed by F-droid contains a tarball of pre-compiled executable binaries.
https://f-droid.org/repo/com.termux_118.apk
`/lib/arm64-v8a/libtermux-bootstrap.so` is a tar compressed file containing a number of executable pre-compiled binaries.
How did F-droid build `libtermux-bootstrap.so`?
It seems that the binary is not the one that F-droid built from source, but the one downloaded from Github.

**Comment by shiftrot** [comment]
My previous reply is a bit off topic, so I'll add to it.

What I want to know is how to build an apk that contains pre-compiled binaries without violating F-droid's security policy.
How does Termux make that possible?
(I'm not interested in talking about the security of F-droid)

DroidVim is releasing the latest Vim executables and runtime libraries as a zip on github.
https://github.com/shiftrot/droidvim/releases
https://github.com/shiftrot/droidvim/releases/download/v2.2.6/binaries.zip
(The latest pre-compiled binaries are not included in the repository to prevent bloat.)

This means that simply cloning and building the DroidVim repository locally will not keep the Vim executable up-to-date.
This is a bit of a problem, so I am thinking of changing it to download the latest binaries from Github and build them like Termux does.
If I can support F-droid by adding a small twist to this change, I'd like to try it.

Thanks.

**Comment by opk12** [comment]
> how to build an apk that contains pre-compiled binaries

It is not possible. The Termux build script should be patched, thank you for reporting (forwarded in the issue linked above).


The current approach of providing vim separately requires manual, repeated work for you and for each and every end user. Could the build script automate building vim? If so, updating vim would mean to hard-code a version number and tag the release; the app stores would do the rest.

Doing this upstream would also save work to F-Droid and be a step forward for the inclusion. The f-droid.org instance builds on Debian stable, so scripts for Ubuntu would likely work unpatched.

**Comment by shiftrot** [comment]
- In order for DroidVim to comply with Google Play's security policy, the executable binaries (E.g. Vim) in the apk must be implemented in a way that cannot be modified.
- The purpose of my script is to automate the building and uploading of DroidVim to Google Play, and is not intended to be generic.
- Since Vim is open source and the build method is publicly available, anyone can build it. It would be preferable for someone who is familiar with F-droid to write a binary build script for F-droid. (Vim binary built for Termux should also work with DroidVim).

I would appreciate it if you could let me know if you get any conclusion from F-droid about the Termux build.
If it can be easily supported, DroidVim may also support F-droid.

**Comment by shiftrot** [comment]
License file has been added.
If there is no problem with the license, I think the rest is on the F-Droid side.
Thanks

**Comment by opk12** [comment]
> * In order for DroidVim to comply with Google Play's security policy, the executable binaries (E.g. Vim) in the apk must be implemented in a way that cannot be modified.

I cannot find this in google play's policies, can you point me to the docs/source? Thanks

**Comment by shiftrot** [comment]
https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission
This is the reason why Termux gave up distribution on Google Play.
F-droid tries to avoid the risk of allowing insecure apps by building all files from open source.
However, F-droid seems to only check that the repository does not contain binary files.

**Comment by opk12** [comment]
Thank you, but that section forbids to compile and run vim *after installation*. It does not forbid to run a gradle-compiled vim (quote) `embedded within an app's APK file`. In general, Play Store apps can bundle and call a native library or a standalone binary, but a good comparison in the specific case of this app is [Aria2App](https://f-droid.org/en/packages/com.gianlu.aria2app/).

The logical problem of labeling a software as "secure" is well-known in the software industry to be unsolvable, both in theory and in practice. F-Droid sidesteps it by sticking to the fact that the package is reproducible (malicious or not) i.e. matches the source code. This is the state of the art and is also the standard on the desktop GNU/Linux distros.

**Comment by shiftrot** [comment]
> Thank you, but that section forbids to compile and run vim *after installation*. It does not forbid to run a gradle-compiled vim (quote) `embedded within an app's APK file`. In general, Play Store apps can bundle and call a native library or a standalone binary, but a good comparison in the specific case of this app is [Aria2App](https://f-droid.org/en/packages/com.gianlu.aria2app/).

I gave you that link for your question and I think I understand the content.
That's why DroidVim, which is distributed on Google Play, embeds the executable binary instead of downloading or unzipping it.
What is your problem? Which do you want to talk about Google Play or F-droid?

> The logical problem of labeling a software as "secure" is well-known in the software industry to be unsolvable, both in theory and in practice. F-Droid sidesteps it by sticking to the fact that the package is reproducible (malicious or not) i.e. matches the source code. This is the state of the art and is also the standard on the desktop GNU/Linux distros.

DroidVim can be built only from the source on Github, so there should be no problem.
Why did F-droid reject DroidVim?
You said pre-compiled binaries are the problem.
https://f-droid.org/repo/com.termux_118.apk
`/lib/arm64-v8a/libtermux-bootstrap.so` is a tar compressed file containing a number of executable pre-compiled binaries. (The apk file can be unzipped by renaming it to .zip.)
How did F-droid build `libtermux-bootstrap.so`?

What I want to know is how Termux creates `libtermux-bootstrap.so` under F-droid policy.
Thanks.

**Comment by linsui** [comment]
I reported the Termux problem upstream. We are going to build the bootstraps packages from source along with the Termux app. The [step](https://github.com/termux/termux-packages) is pretty easy. The problem with building droidvim is that I can't find the step to build binaries in https://github.com/shiftrot/droidvim/tree/master/term/src. Could you please help? Thanks!

**Comment by shiftrot** [comment]
Could you let me know when F-Droid will be able to build applications such as Termux and UserLand from source?

Technically, it should be possible to build it by simply adding Vim to the Termux bootstrap binary and making a few modifications.
Perhaps F-Droid needs to provide a complete VM, network and root.

If F-Droid is unable to provide a VM, the easiest way is to lower the target API level of the app and change it to automatically download the executable binary at boot time.
I don't want to call it a secure app, but F-Droid should be satisfied.

**Comment by linsui** [comment]
> Could you let me know when F-Droid will be able to build applications such as Termux and UserLand from source?

See https://github.com/termux/termux-app/issues/2892.

> Technically, it should be possible to build it by simply adding Vim to the Termux bootstrap binary and making a few modifications.
> Perhaps F-Droid needs to provide a complete VM, network and root.

The buildserver is a Debian VM. I'm not sure if a nest VM works. But I guess if we can build the Termux package we can build droidvim?

**Comment by marek22k** [comment]
Are there any news? It it still not on F-Droid.
