### ISSUE TITLE
It's possible to automate Google Drive file open?

### ISSUE THREAD

**Issue by liamtrinalizo** [shiftrot/droidvim#62]
Is there a way to set a function key command to open a specific file in Google Drive ?
Like F1 command = `:edit googledrive/name@gmail.com/foo/bar/test.txt` 

I'm always opening the same file several times a day in Drive and having to go through the file selector takes too long.

Great App BTW

**Comment by shiftrot** [comment]
GoogleDrive files are stripped of write permission after a short period of time after the file is opened.
Therefore, in the case of GoogleDrive, the file must be reopened using a file chooser.
Probably for security reasons. For many other storage files, write permission persists when opened via File Chooser.

The easiest solution is to use a file synchronization app to access the files.
https://play.google.com/store/apps/details?id=com.ttxapps.drivesync

The MRU menu is an easy way to re-open files on external storage.
Cache files can also be opened directly from Vim.  (However, validity is not verified when the file is opened.)
If you want to register to the F1 key, you can use the path to the cache file.
I recommend using the latest version of Google Play because the cache file path is shorter.

**Comment by liamtrinalizo** [comment]
Thank you for the quick answer, I will try it out
