### ISSUE TITLE
[feature missing] option to set gesture to `<esc>` or  `:` or `/` no longer available?

### ISSUE THREAD

**Issue by m2habert** [shiftrot/droidvim#70]
I don't get it: I've recently updated droidVim and the "send esc" option for gestures/double-taps  is no longer there!

Also missing are the ":" and the "/" for easy search.

¿what happened? Is this a bug?

Thanks in advance.

**Comment by shiftrot** [comment]
I intentionally removed these settings because I did not think it made sense to use gestures to key in rather than function keys that are entered with a single tap.
Wouldn't it be more convenient to use the ESC key with one tap instead of gestures?

Reverting back itself is easy and can be enabled in the next update.
Personally, I recommend reviewing your function key settings.
Could you post a screenshot if possible so I can see how you are using the function bar?

**Comment by m2habert** [comment]
![photo1683576894](https://user-images.githubusercontent.com/7454005/236925538-f7efbfa2-63ad-4e75-9b48-a7fe4f49a444.jpeg)

1 - (red) awfully tiny and midway located long-press for `:` and `/`

2 - (orng) I select function bar keys in  order to keep the quit and keyboard buttons comfortably on the right side as I'm always using these two buttons, and as I mostly use right-hand (= right hand thumb) 

3 - (green) distant "in-the-left-field" `ESC` key for the right-hand user

**Comment by shiftrot** [comment]
Thanks.
I will consider reverting it in the next update.
